name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.9.1", "5.7.3"]

    container:
      image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
